import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { Utensils } from 'lucide-react';
export default function MealSelector({ perfil, comidas, dia, momento, selecciones, onToggle, accentClasses, }) {
    return (_jsx("div", { className: "grid gap-3", children: comidas.map((comida, idx) => {
            const esSeleccionada = selecciones[`${perfil}-${dia}-${momento}-${comida.nombre}`];
            return (_jsx(motion.div, { initial: { opacity: 0, scale: 0.95 }, animate: { opacity: 1, scale: 1 }, whileTap: { scale: 0.97 }, transition: { type: 'spring', stiffness: 400, damping: 30, delay: idx * 0.04 }, onClick: () => onToggle(perfil, dia, momento, comida.nombre), className: `relative overflow-hidden rounded-[24px] sm:rounded-3xl transition-all duration-300 cursor-pointer group ${esSeleccionada
                    ? `${accentClasses.bgLight} border-[2.5px] ${accentClasses.borderAccent} shadow-[0_8px_30px_rgb(0,0,0,0.04)]`
                    : 'bg-white border border-slate-100/80 shadow-sm hover:border-slate-200 hover:shadow-md'}`, children: _jsxs("div", { className: "relative p-5 sm:p-6 space-y-3", children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h4", { className: "font-bold text-slate-800 text-sm tracking-tight leading-snug", children: comida.nombre }), _jsx("p", { className: "text-xs text-slate-500 mt-1 font-medium leading-relaxed", children: comida.detalle })] }), _jsx("div", { className: `w-7 h-7 rounded-full border-[2.5px] flex items-center justify-center flex-shrink-0 transition-all duration-300 ${esSeleccionada
                                        ? `${accentClasses.bg} ${accentClasses.borderAccent} scale-110`
                                        : 'border-slate-200 group-hover:border-slate-300 bg-slate-50'}`, children: esSeleccionada && (_jsx(motion.div, { initial: { scale: 0 }, animate: { scale: 1 }, transition: { type: 'spring', stiffness: 500, damping: 30 }, children: _jsx("svg", { className: "w-4 h-4 text-white", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor", strokeWidth: 3, children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", d: "M5 13l4 4L19 7" }) }) })) })] }), _jsx("div", { className: "pt-1", children: _jsxs("div", { className: `flex items-center gap-3 text-xs bg-white rounded-[16px] p-3 border ${esSeleccionada ? accentClasses.border : 'border-slate-100'} shadow-sm`, children: [_jsx("div", { className: `w-7 h-7 rounded-[10px] ${accentClasses.bgLight} flex items-center justify-center flex-shrink-0`, children: _jsx(Utensils, { className: `w-3.5 h-3.5 ${accentClasses.text}` }) }), _jsx("span", { className: "text-slate-700 font-medium tracking-tight leading-relaxed", children: comida.porciones })] }) }), _jsxs("div", { className: "flex flex-col gap-2 pt-2 border-t border-slate-100", children: [comida.tags.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-1.5 pt-1", children: comida.tags.map((tag) => (_jsx("span", { className: `inline-flex items-center px-2.5 py-1 rounded-full ${accentClasses.tagBg} ${accentClasses.tagText} text-[9px] uppercase tracking-widest font-extrabold`, children: tag }, tag))) })), comida.super.length > 0 && (_jsx("div", { className: "flex flex-wrap gap-1.5 mt-1", children: comida.super.map((ing) => (_jsx("span", { className: "inline-block px-2.5 py-1 bg-slate-100 text-slate-500 rounded-lg text-[10px] font-semibold tracking-tight", children: ing }, ing))) }))] })] }) }, comida.nombre));
        }) }));
}
